@baseUrl = http://localhost:8080
@json = application/json

### ------------------------------------------------------------
### Health check
### ------------------------------------------------------------
GET {{baseUrl}}/
Accept: {{json}}

### ------------------------------------------------------------
### SETUP: Create two users (used for friends + ownership)
### ------------------------------------------------------------
# @name createUser1
POST {{baseUrl}}/users
Accept: {{json}}
Content-Type: {{json}}

{"userinfo": {"email": "user1@email.com","sub": "auth0|user1","picture": "Image Path/File"}}

###

# @name createUser2
POST {{baseUrl}}/users
Accept: {{json}}
Content-Type: {{json}}

{
  "userinfo": {
    "email": "user2@email.com",
    "sub": "auth0|user2",
    "picture": "Image Path/File"
  }
}

### ------------------------------------------------------------
### USERS: GET all + GET by id
### ------------------------------------------------------------
GET {{baseUrl}}/users
Accept: {{json}}
###
GET {{baseUrl}}/users/{{createUser1.response.body.U_ID}}
Accept: {{json}}

### ------------------------------------------------------------
### FRIENDS (one-way)
### ------------------------------------------------------------
# Add user2 as friend of user1
PATCH {{baseUrl}}/users/{{createUser1.response.body.U_ID}}/users/{{createUser2.response.body.U_ID}}
Accept: {{json}}
###
# Verify user1 has friend
GET {{baseUrl}}/users/{{createUser1.response.body.U_ID}}
Accept: {{json}}
###
# Verify user2 does NOT have user1 as friend (one-way)
GET {{baseUrl}}/users/{{createUser2.response.body.U_ID}}
Accept: {{json}}
###
# Remove friend
DELETE {{baseUrl}}/users/{{createUser1.response.body.U_ID}}/users/{{createUser2.response.body.U_ID}}
Accept: {{json}}

### ------------------------------------------------------------
### ARTS: Create + list + get + delete
### ------------------------------------------------------------
# @name createArt
POST {{baseUrl}}/arts
Accept: {{json}}
Content-Type: {{json}}

{
  "User": { "U_ID": {{createUser1.response.body.U_ID}} },
  "A_Title": "Starry Night",
  "A_Image": "Image Path/File",
  "A_Is_Public": true,
  "A_Comments": []
}
###
GET {{baseUrl}}/arts?limit=10&offset=0
Accept: {{json}}
###
GET {{baseUrl}}/arts/{{createArt.response.body.A_ID}}
Accept: {{json}}
###
DELETE {{baseUrl}}/arts/{{createArt.response.body.A_ID}}
Accept: {{json}}
###
# Verify deleted
GET {{baseUrl}}/arts/{{createArt.response.body.A_ID}}
Accept: {{json}}

### ------------------------------------------------------------
### GALLERIES: Create + list + get + delete
### ------------------------------------------------------------
# @name createGallery
POST {{baseUrl}}/galleries
Accept: {{json}}
Content-Type: {{json}}

{
  "User": { "U_ID": {{createUser1.response.body.U_ID}} },
  "G_Name": "My Gallery",
  "G_Is_Public": false,
  "G_Comments": []
}
###
GET {{baseUrl}}/galleries?limit=10&offset=0
Accept: {{json}}
###
GET {{baseUrl}}/galleries/{{createGallery.response.body.G_ID}}
Accept: {{json}}
###
DELETE {{baseUrl}}/galleries/{{createGallery.response.body.G_ID}}
Accept: {{json}}
###
# Verify deleted
GET {{baseUrl}}/galleries/{{createGallery.response.body.G_ID}}
Accept: {{json}}

### ------------------------------------------------------------
### CLEANUP: Delete users
### ------------------------------------------------------------
DELETE {{baseUrl}}/users/{{createUser1.response.body.U_ID}}
Accept: {{json}}
###
DELETE {{baseUrl}}/users/{{createUser2.response.body.U_ID}}
Accept: {{json}}

### ------------------------------------------------------------
### CONTRACT NEGATIVES (minimal but valuable)
### ------------------------------------------------------------

# 406: wrong Accept
GET {{baseUrl}}/users
Accept: text/html
###
# 415: missing content-type for json endpoint
POST {{baseUrl}}/users
Accept: {{json}}

{
  "userinfo": { "email": "bad@email.com" }
}
###
# 400: body not allowed
GET {{baseUrl}}/users
Accept: {{json}}

{ "bad": true }
